### PR TITLE
Gentle shortening using built-in abbreviate-file-name

### PR DESCRIPTION
**Pull request by a13**
See screenshot:

diff

### CODE REVIEW

**Comment by Yevgnen** [comment]
Hello! Sorry for late reply here and thanks for your work. It's quite a nice feature and I'm grad to merge it. But there's a small bug when `(setq ivy-rich-abbreviate-paths t)` and using `projectile`, the relative path of the file to the project root is break by `ivy-rich-abbreviate-path`. Of course, a more elaborate way to find the relative path to the project root should be used, but currently I have no time😅 to fix this and maybe a new commit could avoid this?

**Comment by a13** [comment]
Oh, sorry, I don't use projectile, so couldn't see the bug. Will check it out and fix it ASAP!

**Comment by a13** [comment]
BTW, could you please tell me, how can I reproduce the bug?

**Comment by Yevgnen** [comment]
Hi,

Eval your newest commit and and enable `projectile`. Then open a file under a 'project', which contains a `.git` or `.svn` etc. `(setq ivy-rich-abbreviate-paths t)` and run the switch buffer command you will see 
screen shot 2017-02-22 at 4 54 45 pm
compared to `(setq ivy-rich-abbreviate-paths nil)`
screen shot 2017-02-22 at 4 57 32 pm

This is due to my naive implement of getting the relative path to a project root [here](https://github.com/a13/ivy-rich/blob/d5cb9de6f84a4ea8f824b46648905e5c8221f10a/ivy-rich.el#L203). 

You may fix this in an individual pull request and I am grad to merge both. Sorry for having no time on testing and developing it right now. Thank you!

**Comment by a13** [comment]
I see, thanks!

**Comment by a13** [comment]
ivy-rich
It looks fixed for me now :)

**Comment by Yevgnen** [comment]
Hello,

Thanks for you work. The `str` is actually an issue. But I think it should be an individual fix. Sorry for late reply again.

**Comment by a13** [comment]
Should I revert the latest commit then?

**Comment by Yevgnen** [comment]
I think you should revert to https://github.com/Yevgnen/ivy-rich/pull/12/commits/e3d6f426a14903baccf897da391eb467f63f2b95 .

**Comment by Yevgnen** [comment]
I'm having a busy new year right now and sorry again for late. Thank you!

**Comment by a13** [comment]
It's ok! Thank you!

**Pull request merged**
