### PR TITLE
Add all-the-icons support.

### PR DESCRIPTION
**Pull request by a13**
all-the-icons

More bells and whistles.

### CODE REVIEW

**Comment by a13** [comment]
There's an "all-the-icons-ivy" package, but it doesn't work well with ivy-rich, so I decided to add this feature.

**Comment by Yevgnen** [comment]
Hi, that's a very nice feature.

But `all-the-icons` may has performance in some platform so it would be better to have an option to enable the feature. An related feature request [#17](https://github.com/Yevgnen/ivy-rich/pull/17) is to have customizable displaying columns. I might add this later and make a pr to adjust your commits.

**Comment by a13** [comment]
> But all-the-icons may has performance in some platform so it would be better to have an option to enable the feature. 

Everything is simple - It won't be used if it's not installed :)

**Comment by Yevgnen** [comment]
Sorry for late reply. We are have a busy new year here. 😂

screen shot 2018-02-26 at 12 04 24 pm

It seems that the icon need to be manually adjusted with my font(passing `:height` or `:v-adjust` to `all-the-icons-icon-for-mode`) since it make the minibuffer add many 'newline' in the bottom. 


Adding 

```elisp

(defun ivy-rich-switch-buffer-buffer-icon ()
  "Try to find the icon for the buffer's `major-mode'.
If that fails look for an icon for the mode that the `major-mode' is derived from."
  (when (require 'all-the-icons nil t)
    (format "%s\t"
            (propertize "\t" 'display
                        (let ((icon (all-the-icons-icon-for-mode major-mode :height 0.7 :v-adjust 0.05)))
                          (if (symbolp icon)
                              (all-the-icons-icon-for-mode 'fundamental-mode :height 0.7 :v-adjust 0.05)
                            icon))))))
```

results in

screen shot 2018-02-26 at 12 20 17 pm

Do you have a better way for user to adjust this?

Also I prefer "" to "\t" between the icon and the buffer name, how to you think about this?

**Comment by qleguennec** [comment]
Any news on this? That feature would be awesome.

**Pull request closed without merging**
