### PR TITLE
Add Magit integration

### PR DESCRIPTION
**Pull request by EgorDuplensky**
Display additional information, such as
remote branch, commit sha, tag, commit subject
when selecting magit revisions

### CODE REVIEW

**Comment by EgorDuplensky** [comment]
@Yevgnen Could you please try the changes and see if you can consider this feature to be included

**Comment by EgorDuplensky** [comment]
<details>
<summary>There is an example of _magit-checkout_ command</summary>

ivy-rich-magit-example
</details>

**Comment by a13** [comment]
it's fun, today I got an idea that it would be great to extend `ivy-rich` with stuff like that (I work on a lot of branches all the time and sometimes branch names are not enough)

@Yevgnen friendly ping

**Comment by EgorDuplensky** [comment]
@Yevgnen Could you please leave a comment.
I am ok to close the PR if you are not planning to add this feature

**Comment by Yevgnen** [comment]
Hi, guys. I'm sorry I missed the messages in the past years. I switched to `consult` those days and then switched to other editor for programming due to the poor performance of Emacs. I'm afraid I'm not gonna merge any new feature for this package. I also recommend `consult` and `marginalia` to get better user experience for displaying this kind of information.

**Comment by EgorDuplensky** [comment]
> Hi, guys. I'm sorry I missed the messages in the past years. I switched to `consult` those days and then switched to other editor for programming due to the poor performance of Emacs. I'm afraid I'm not gonna merge any new feature for this package. I also recommend `consult` and `marginalia` to get better user experience for displaying this kind of information.

Not worries, closing then.
May I ask what have you traded emacs for if it's not a secret? :smirk:

**Comment by Yevgnen** [comment]
@EgorDuplensky 

Sure. Now I mainly use `Zed` to coding and sometimes `Helix` when GUI is unavailable. Both pretty new and everything work out of the box and more importantly being blazing fast. Both does not support plugins yet but the application is under active development. I don't need to face any legacy like those 12 years with Emacs.

I still using Emacs except writing codes, mainly with `dired`, `magit` and sometimes `org-mode` for taking notes. They are still great packages. I like the idea that treating everything like text object to work with in Emacs by only using the keyboard, but the performance of Emacs upsets me too often.

**Pull request closed without merging**
