### PR TITLE
Increase performance of calculating the project in switch buffer

### LINKED ISSUE #46: Use buffer-local-value instead of with-current-buffer
Just saw [this link](https://github.com/alphapapa/emacs-package-dev-handbook#best-practices).
As `ivy-rich` uses a lot of `with-current-buffer` and speed for ivy
is important, maybe it's a good idea to switch whenever possible to `buffer-local-value`?

### PR DESCRIPTION
**Pull request by CeleritasCelery**
I was encountering a lot of issues with ivy-switch-buffer and was consistently maxing out the `max-specpdl-size` no matter how high I set it. I did some tracing and found out that it was because we were using `with-current-buffer`, which is [very slow](https://github.com/alphapapa/emacs-package-dev-handbook#accessing-buffer-local-variables) and expensive. I switched to using `ivy-rich--local-values` and the performance problems went away. 

Note that I use project.el, not projectile because the latter has terrible performance and there is not much that we can do to fix that. Though I did test it with projectile to make sure it worked.  

Closes #46

### CODE REVIEW

**Comment by Yevgnen** [comment]
Sorry for late reply and thanks for the PR. I fixed some of the `with-current-buffer` issues before and left some tough ones... I'll take a look of this maybe this weekend.

**Comment by Yevgnen** [comment]
The PR looks fine overall. I notice two changes that may be inconsistent with the old version.

1. `ivy-rich-switch-buffer-project` now use directory name of project root as project name, while there could be possible customized project name like the one set by `projectile-project-name`, though it's not a really big deal.

2. `ivy-rich--switch-buffer-root-and-filename` does not respect `ivy-rich-parse-remote-file-path` when getting root directory and filename for buffer candidates.

**Comment by CeleritasCelery** [comment]
> ivy-rich-switch-buffer-project now use directory name of project root as project name, while there could be possible customized project name like the one set by projectile-project-name, though it's not a really big deal.

I would say leave it as is, but that is your call. It would make the code a little less straight forward but is doable. 

> ivy-rich--switch-buffer-root-and-filename does not respect ivy-rich-parse-remote-file-path when getting root directory and filename for buffer candidates.

It didn't respect that before. But it is only used in `ivy-rich-switch-buffer-path` which does respect that variable.

**Comment by Yevgnen** [comment]
My bad... It was a copy-paste mistake. I meant `ivy-rich-parse-remote-buffer`. But I now think it's unnecessary since `ivy-rich--switch-buffer-root-and-filename` and it are controlled in different places as long as `ivy-rich--switch-buffer-directory` is efficient enough.

**Pull request merged**
